# -*- coding: utf-8 -*-
"""TESTE Intuitive Care.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XCdOIymhxeLL45kb60YEOlISDemXK5Ub
"""

!pip install PyPDF2
!pip install tabula-py
import os
from zipfile import ZipFile, ZIP_DEFLATED
import requests
from bs4 import BeautifulSoup
from PyPDF2 import PdfReader
import tabula
import pandas as pd

url = 'https://www.gov.br/ans/pt-br/acesso-a-informacao/participacao-da-sociedade/atualizacao-do-rol-de-procedimentos'
pagina = requests.get(url)
soup = BeautifulSoup(pagina.text, 'html.parser')

pdf_links = []
for link in soup.find_all('a', href=True):
    if ('Anexo I' in link.text or 'Anexo II' in link.text) and link['href'].lower().endswith('.pdf'):
        pdf_links.append(link['href'])

os.makedirs('downloads', exist_ok=True)
for pdf_url in pdf_links:
    pdf_url = pdf_url if pdf_url.startswith("http") else f"https://www.gov.br{pdf_url}"
    pdf_name = os.path.join('downloads', os.path.basename(pdf_url))
    with open(pdf_name, 'wb') as pdf_file:
        pdf_file.write(requests.get(pdf_url).content)

with ZipFile('anexos.zip', 'w') as zipf:
    for file in os.listdir('downloads'):
        zipf.write(os.path.join('downloads', file), file)

print("Download e compactação concluídos!")

pdf_path = 'downloads/Anexo_I_Rol_2021RN_465.2021_RN627L.2024.pdf'
pdf_reader = PdfReader(pdf_path)
num_paginas = len(pdf_reader.pages)

tabelas = tabula.read_pdf(pdf_path, pages=list(range(3, num_paginas + 1)))

tabelas_df = pd.concat(tabelas)

tabelas_df.to_csv('tabelas.csv', index=False, encoding='utf-8-sig')

seu_nome = "Victor"
zip_filename = f"Teste_{seu_nome}.zip"

with ZipFile(zip_filename, 'w', ZIP_DEFLATED) as zipf:
    zipf.write('tabelas.csv')

print(f"Arquivo {zip_filename} criado com sucesso!")

arquivo_csv = "tabelas.csv"

with open(arquivo_csv, "r", encoding="utf-8") as f:
    linhas = f.readlines()

linhas_modificadas = [linha.replace("OD", "Seg. Odontológica").replace("AMB", "Seg. Ambulatorial") for linha in linhas]

with open(arquivo_csv, "w", encoding="utf-8") as f:
    f.writelines(linhas_modificadas)

print("Modificação concluída!")

